project:
  type: website

website:
  title: "Statistiques et R"
  favicon: logo_mstats_bleu.png
  back-to-top-navigation: true
  page-footer:
    center:
    - icon: twitch
      href: https://www.twitch.tv/marievaugoyeau
    - icon: envelope
      href: https://mvaugoyeau.kessel.media?source_type=social_network&source_referral=blog
    - icon: linkedin
      href: https://www.linkedin.com/in/marie-vaugoyeau-72ab64153/ 
    - icon: github
      href: https://github.com/Vaugoyeau
    - icon: rss
      href: index.xml
  navbar:
    right:
      - about.qmd
      - text: "S'inscrire Ã  la newsletter"
        href: https://mvaugoyeau.kessel.media?source_type=social_network

      
format:
  html:
    theme: output_style.scss
    fontcolor: rgb(57,119,160)
    backgroundcolor: white
    css: styles.css

editor: visual

execute:
  freeze: auto
